# Generated by Django 5.0.6 on 2024-07-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management_system_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_covers/'),
        ),
    ]
